### ISSUE TITLE
Singularity

### ISSUE THREAD

**Issue by maxim-belkin** [Linuxbrew/homebrew-extra#58]
linuxbrew/extra provides singularity 2.6.0
Latest Singularity 2 version is 2.6.1
Latest Singularity 3 version is 3.2.1

I suggest renaming singularity to singularity@2 and updating it to 2.6.1 (in which order should we do it? Or shall we do it in one PR?) 

I also suggest creating singularity@3.

CC @sjackman

**Comment by sjackman** [comment]
Let's bump `singularity` to version 2.6.1 in one PR.
Then bump `singularity` to version 3.2.1 in a second PR.
Then add `singularity@2` in a third PR, but only if a user asks for it, or you personally have a need for it.

**Comment by sjackman** [comment]
Does Singularity have any support at all for running on macOS. Even if it can't run the containers on macOS, can it build an executable that is able to inspect and modify the disk image files? If so, the `singularity` formula can be moved to `Homebrew/homebrew-core`.

**Comment by maxim-belkin** [comment]
Singularity can run on macOS: https://sylabs.io/guides/3.2/user-guide/installation.html#mac
But installation procedure is different...

**Comment by sjackman** [comment]
Would you be interested in porting this formula to macOS?
